// preguntas.js
export const bancoPreguntas = {
    tranquilo: [
        "¿Cuál es tu recuerdo favorito de nosotros?",
        "¿Qué es lo que más te gusta de mi físico?",
        "¿Cuál sería nuestra cita perfecta?",
        "¿Qué canción te recuerda a mí?",
        "Si pudiéramos viajar mañana, ¿a dónde iríamos?",
        "¿Qué comida te gustaría que cocinemos juntos?",
        "¿Cuál es tu película favorita para ver abrazados?",
        "¿Qué detalle pequeño mío te hace sonreír?",
        "¿Cómo describirías nuestro amor en una palabra?",
        "¿Qué regalo te gustaría recibir ahora mismo?",
        "¿Cuál fue tu primera impresión de mí?",
        "¿Qué superpoder te gustaría tener?",
        "¿Perros o gatos? ¿Por qué?",
        "¿Cuál es tu lugar favorito en el mundo?",
        "¿Qué actividad te relaja más?",
        "¿Prefieres playa o montaña?",
        "¿Qué harías con un millón de dólares?",
        "¿Cuál es tu serie de confort?",
        "¿Qué prenda de ropa mía te gusta más?",
        "¿A qué edad te gustaría retirarte?",
        "¿Qué es lo más loco que has comido?",
        "¿Te gusta dormir abrazados o separados?",
        "¿Cuál es tu estación del año favorita?",
        "¿Qué talento oculto tienes?",
        "¿Cuál es tu postre favorito?",
        "¿Te gustaría vivir en otro país?",
        "¿Qué te hace reír a carcajadas?",
        "¿Cuál es tu día festivo favorito?",
        "¿Prefieres salir de fiesta o ver Netflix?",
        "¿Cuál es tu color favorito en mí?",
        "¿Qué foto nuestra te gusta más?",
        "¿Qué apodo cariñoso te gusta más?",
        "¿Cuál es tu juego de mesa favorito?",
        "¿Te consideras madrugador o nocturno?",
        "¿Qué olor te trae buenos recuerdos?",
        "¿Cuál es tu mayor manía?",
        "¿Qué es lo que más te gusta de ti mismo/a?",
        "¿Te gustaría tener hijos algún día?",
        "¿Cuál es tu bebida favorita?",
        "¿Qué idioma te gustaría aprender?",
        "¿Qué instrumento te gustaría tocar?",
        "¿Cuál fue el mejor año de tu vida?",
        "¿Qué cosa no perdonarías nunca?",
        "¿Qué te da miedo?",
        "¿Crees en el destino?",
        "¿Qué cambiarías de tu rutina diaria?",
        "¿Cuál es tu flor favorita?",
        "¿Te gusta cocinar o que te cocinen?",
        "¿Qué es lo primero que ves en una persona?",
        "¿Te consideras celoso/a?",
        // --- NUEVAS TRANQUILO ---
        "¿Cuál es el mejor cumplido que te han hecho?",
        "¿Qué objeto material tiene más valor sentimental para ti?",
        "¿Cuál es tu mayor sueño por cumplir?",
        "¿Qué prefieres: desayuno en la cama o cena elegante?",
        "¿Cuál es tu red social favorita?",
        "¿Qué es lo más aventurero que has hecho?",
        "¿Cuál es tu sabor de helado preferido?",
        "¿Qué tipo de libros te gusta leer?",
        "¿Cuál es tu época de la historia favorita?",
        "¿Qué prefieres: dulce o salado?",
        "¿Cómo sería tu casa de ensueño?",
        "¿Qué es lo más vergonzoso que te ha pasado?",
        "¿Cuál es tu aplicación del móvil que más usas?",
        "¿Qué harías si hoy fuera un día festivo solo para nosotros?",
        "¿Cuál es tu tradición familiar favorita?",
        "¿Qué es lo que más te gusta de los fines de semana?",
        "¿Cuál es tu ciudad favorita del mundo?",
        "¿Qué habilidad nueva te gustaría desarrollar?",
        "¿Prefieres el amanecer o el atardecer?",
        "¿Qué es lo más amable que has hecho por un extraño?",
        "¿Cuál es tu juego de cartas favorito?",
        "¿Qué superpoder elegirías: volar o ser invisible?",
        "¿Cuál es tu mayor logro hasta ahora?",
        "¿Qué te hace sentir más orgulloso/a de nuestra relación?",
        "¿Cuál es tu snack favorito para ver una película?"
    ],
    profundo: [
        "¿Qué es lo que más valoras de nuestra relación?",
        "¿Hay algo que te preocupe y no me hayas dicho?",
        "¿Cómo nos ves en 5 años?",
        "¿Qué he hecho que te haya hecho sentir muy amado/a?",
        "¿Qué obstáculo crees que hemos superado mejor?",
        "¿Qué significa la confianza para ti?",
        "¿Qué puedo hacer para apoyarte más en tus sueños?",
        "¿Hay algo del pasado que debamos perdonar?",
        "¿Qué es lo que más admiras de mi personalidad?",
        "¿Por qué me elegiste a mí?",
        "¿Cuál es tu mayor miedo en la vida?",
        "¿Qué momento de tu infancia te marcó más?",
        "¿Qué cambiarías de tu forma de ser?",
        "¿Qué crees que nos falta mejorar como pareja?",
        "¿Cuándo te sientes más vulnerable?",
        "¿Qué significa para ti el éxito?",
        "¿Hay algo de lo que te arrepientas mucho?",
        "¿Cómo te gustaría ser recordado/a?",
        "¿Qué lección dolorosa has aprendido?",
        "¿Sientes que puedes ser tú mismo/a conmigo al 100%?",
        "¿Qué sacrificio harías por amor?",
        "¿Cuál es tu lenguaje del amor principal?",
        "¿Qué te hace sentir inseguro/a a veces?",
        "¿Qué es lo que más agradeces hoy?",
        "¿Crees en las almas gemelas?",
        "¿Qué harías si hoy fuera tu último día?",
        "¿Qué es lo que más te estresa actualmente?",
        "¿Cómo manejas la tristeza?",
        "¿Qué esperas de mí como compañero/a de vida?",
        "¿Qué sueño has abandonado y por qué?",
        "¿Qué te motiva a levantarte cada día?",
        "¿Qué es lo más difícil que has tenido que hacer?",
        "¿Qué opinas de la infidelidad?",
        "¿Qué valor es innegociable para ti?",
        "¿Cómo te llevas con tu familia?",
        "¿Qué te gustaría cambiar de nuestro pasado?",
        "¿Qué promesa te gustaría hacerme?",
        "¿Cuándo fue la última vez que lloraste?",
        "¿Qué te hace sentir orgulloso/a de mí?",
        "¿Qué necesitas de mí cuando estás mal?",
        "¿Crees que el amor dura para siempre?",
        "¿Qué error no volverías a cometer?",
        "¿Qué consejo le darías a tu yo del pasado?",
        "¿Qué es lo que más te cuesta expresar?",
        "¿Te siente valorado/a en la relación?",
        "¿Qué meta tenemos en común que te emociona?",
        "¿Qué hábito mío te molesta un poco?",
        "¿Qué es lo más bonito que alguien ha hecho por ti?",
        "¿Cómo defines la felicidad?",
        "¿Qué secreto no le has contado a nadie?",
        // --- NUEVAS PROFUNDO ---
        "¿Qué es lo que más te asusta de envejecer?",
        "¿Qué parte de tu pasado te ha hecho más fuerte?",
        "¿Cómo te gustaría que fuera nuestra vida en la vejez?",
        "¿Qué es lo que más te gusta de nuestra comunicación?",
        "¿Qué sientes que nos hace únicos como pareja?",
        "¿Cuál es tu definición personal de amor?",
        "¿Qué es lo que más te duele de la sociedad actual?",
        "¿Cómo defines la lealtad?",
        "¿Qué es lo que más te ha enseñado nuestra relación?",
        "¿Qué parte de tu personalidad te gustaría que conociera mejor?",
        "¿Cómo manejas el fracaso?",
        "¿Qué es lo que más te inspira de otras personas?",
        "¿Qué importancia tiene la espiritualidad para ti?",
        "¿Cuál es tu mayor remordimiento?",
        "¿Qué es lo que más te gusta de nuestra vida diaria?",
        "¿Qué sientes que es lo más sagrado para ti?",
        "¿Cómo te gustaría que nos apoyáramos en los momentos difíciles?",
        "¿Qué es lo que más te ha sorprendido de ti mismo/a?",
        "¿Qué papel juega el perdón en tu vida?",
        "¿Cómo te gustaría que celebráramos nuestros logros?",
        "¿Qué es lo que más te hace sentir en paz?",
        "¿Qué legado te gustaría dejar en el mundo?",
        "¿Cómo te gustaría que fuera nuestra relación con nuestras familias?",
        "¿Qué es lo que más te apasiona en la vida?",
        "¿Cómo te gustaría que enfrentáramos los conflictos?"
    ],
    hot: [
        "¿Qué parte de mi cuerpo te enciende más?",
        "Describe una fantasía que quieras cumplir conmigo.",
        "¿Qué ropa interior te gustaría verme puesta?",
        "¿Cuál ha sido nuestro mejor momento íntimo?",
        "¿Te gusta que tome la iniciativa o prefieres hacerlo tú?",
        "¿Un lugar prohibido donde te gustaría hacerlo?",
        "¿Qué te gustaría que te susurre al oído?",
        "¿Luces encendidas o apagadas?",
        "¿Qué juguete te gustaría probar?",
        "Del 1 al 10, ¿qué tantas ganas tienes ahora mismo?",
        "¿Qué posición te gustaría probar hoy?",
        "¿Te gusta el sexo rudo o suave?",
        "¿Qué parte de tu cuerpo te gusta que bese?",
        "Has tenido algún sueño erótico conmigo?",
        "¿Qué te gustaría que te haga con la lengua?",
        "¿Te gustaría grabarnos alguna vez?",
        "¿Qué opinas del sexo oral?",
        "¿Te pone caliente que te envíe fotos?",
        "¿Qué es lo más atrevido que harías en público?",
        "¿Te gustaría usar aceites o masajes?",
        "¿Qué sonido mío te excita más?",
        "¿Te gusta que te muerda suavemente?",
        "¿Mañanero o nocturno?",
        "¿En la ducha o en la cama?",
        "¿Qué palabra te pone a mil?",
        "¿Te gustaría que usemos disfraces?",
        "¿Qué es lo que más te gusta de mi olor?",
        "¿Te gustaría atarme o que te ate?",
        "¿Qué sientes cuando te miro a los ojos mientras lo hacemos?",
        "¿Te gusta hacerlo con música?",
        "¿Cuál es tu zona erógena más sensible?",
        "¿Te gustaría probar hacerlo frente a un espejo?",
        "¿Qué te gustaría que te haga ahora mismo?",
        "¿Cuánto tiempo te gustaría que duremos hoy?",
        "¿Te gusta ver o que te vean?",
        "¿Qué harías si te despierto a medianoche?",
        "¿Te gustaría usar hielo o algo caliente?",
        "¿Qué opinas del sexo telefónico?",
        "¿Te gustaría hacerlo en el coche?",
        "¿Qué lencería te pone más?",
        "¿Te gusta que te tire del pelo?",
        "¿Prefieres arriba o abajo?",
        "¿Qué es lo más sucio que has pensado hoy?",
        "¿Te gusta el dirty talk (hablar sucio)?",
        "¿Qué harías si estuviéramos solos en un ascensor?",
        "¿Te gustaría que te haga un striptease?",
        "¿Qué parte de mi cuerpo te gustaría lamer?",
        "¿Te gusta acabar juntos o por turnos?",
        "¿Qué fantasía te da vergüenza contarme?",
        "¿Te atreverías a hacerlo en la playa de noche?",
        // --- NUEVAS HOT ---
        "¿Qué es lo más salvaje que te gustaría probar?",
        "¿Te gusta que te venda los ojos?",
        "¿Qué parte de mi cuerpo te gustaría explorar más?",
        "¿Cuál es tu mayor fetiche?",
        "¿Te gusta que te nalguee suavemente?",
        "¿Qué tan importante es para ti el juego previo?",
        "¿Te gustaría tener una noche de hotel solo para nosotros?",
        "¿Qué es lo más excitante que te he dicho?",
        "¿Te gusta que te domine o ser dominado/a?",
        "¿Qué harías si te dijera que no llevo ropa interior?",
        "¿Cuál es tu hora favorita para la pasión?",
        "¿Te gusta que te acaricie por encima de la ropa?",
        "¿Qué es lo que más te gusta de mis besos?",
        "¿Te gustaría probar comida sobre el cuerpo?",
        "¿Qué es lo más atrevido que te gustaría que hiciéramos?",
        "¿Te gusta que te mire mientras te tocas?",
        "¿Cuál es tu secreto más picante?",
        "¿Te gustaría que probáramos el bondage suave?",
        "¿Qué es lo que más te gusta de mi reacción al placer?",
        "¿Te gustaría que hiciéramos un juego de roles?",
        "¿Qué es lo más prohibido que has imaginado?",
        "¿Te gusta que te hable al oído mientras lo hacemos?",
        "¿Cuál es tu fantasía más recurrente?",
        "¿Qué es lo más intenso que has sentido conmigo?",
        "¿Te gustaría que pasáramos todo el día en la cama?"
    ]
};